// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('header1', { text: 'PASSWORD' });
    CreateText('header2', { text: 'MAKER' });
    CreateText('mp_lbl', { text: 'Master Password' });
    CreateText('iu_lbl', { text: 'Input URL' });
    CreateText('ul3_lbl', { text: 'Use l33t' });
    CreatePopupButton('usel33t', { leftImageWidth: 10, options: unescape('[[%27not at all%27%2C %27none%27%2C true]%2C [%27before generating password%27%2C %27before-hashing%27]%2C [%27after generating password%27%2C %27after-hashing%27]%2C [%27before and after generating password%27%2C %27both%27]]'), rightImageWidth: 16, onchange: 'usel33t_change' });
    CreateText('ll_lbl', { text: 'l33t Level' });
    CreateText('ha_lbl', { text: 'Hash Algorithm' });
    CreatePopupButton('hashalg', { onchange: 'go_click', options: unescape('[[%27MD4%27%2C %27md4%27]%2C [%27HMAC-MD4%27%2C %27hmac-md4%27]%2C [%27MD5%27%2C %27md5%27]%2C [%27MD5 Version 0.6%27%2C %27md5_v6%27]%2C [%27HMAC-MD5%27%2C %27hmac-md5%27]%2C [%27HMAC-MD5 Version 0.6%27%2C %27hmac-md5_v6%27]%2C [%27SHA-1%27%2C %27sha1%27]%2C [%27HMAC-SHA-1%27%2C %27hmac-sha1%27]%2C [%27SHA-256%27%2C %27sha256%27%2C true]%2C [%27HMAC-SHA-256%27%2C %27hmac-sha256_fix%27]%2C [%27HMAC-SHA-256 Version 1.5.1%27%2C %27hmac-sha256%27]%2C [%27RIPEMD-160%27%2C %27rmd160%27]%2C [%27HMAC-RIPEMD-160%27%2C %27hmac-rmd160%27]]'), rightImageWidth: 16, leftImageWidth: 10 });
    CreateText('l_lbl', { text: 'Length' });
    CreateText('un_lbl', { text: 'Username' });
    CreateText('mod_lbl', { text: 'Modifier' });
    CreateText('chrs_lbl', { text: 'Characters' });
    CreatePopupButton('characters', { leftImageWidth: 10, options: unescape('[[%27Edit character set...%27%2C %27{EDIT}%27%2C true]]'), rightImageWidth: 16, onchange: 'chars_change' });
    CreateText('pr_lbl', { text: 'Prefix' });
    CreateText('sf_lbl', { text: 'Suffix' });
    CreateText('gp_lbl', { text: 'Generated Password' });
    CreatePopupButton('l33tlevel', { onchange: 'go_click', options: unescape('[[%271%27%2C %27%27%2C true]%2C %272%27%2C %273%27%2C %274%27%2C %275%27%2C %276%27%2C %277%27%2C %278%27%2C %279%27]'), rightImageWidth: 16, leftImageWidth: 10 });
    CreateHorizontalLevelIndicator('strength', { imageHeight: 20, maxValue: 100, onValue: 1, criticalValue: 75, imageWidth: 12, warningValue: 50 });
    CreateText('st_lbl', { text: 'Strength' });
    CreateText('text', { text: 'Clear Master Password after' });
}
window.addEventListener('load', setupParts, false);
