var hash,params='201c0008',extras='',version='1';var ie6=false,g=function(id){return document.getElementById(id)};var bklname,protocol,subdomain,domain,path,username,whereleet,leetlevel,hashalgo,length,modifier,prefix,suffix,bookmarklet,error;var characters,cUpper,cLower,cNumber,cSpecial,cDefine,cTabs;window.onload=function(){var hex=Array('0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f');var i;bklname=g('name');protocol=g('protocol');subdomain=g('subdomains');domain=g('domain');path=g('path');username=g('username');whereleet=g('whereleet');leetlevel=g('leetlevel');hashalgo=g('hashalgo');length=g('length');modifier=g('modifier');prefix=g('prefix');suffix=g('suffix');bookmarklet=g('bookmarklet');bookmarklet.appendChild(document.createTextNode(''));error=g('errorMessage');error.appendChild(document.createTextNode(''));characters=g('characters');cUpper=g('charactersUpper');cLower=g('charactersLower');cNumber=g('charactersNumber');cSpecial=g('charactersSpecial');cDefine=g('characterDefined');cTabs=[g('characterPartsTab'),g('characterDefinedTab')];protocol.onclick=protocol.onchange=updateParams;subdomain.onclick=subdomain.onchange=updateParams;domain.onclick=domain.onchange=updateParams;path.onclick=path.onchange=updateParams;bklname.onkeyup=bklname.onchange=updateParams;username.onkeyup=username.onchange=updateParams;length.onkeyup=length.onchange=updateParams;modifier.onkeyup=modifier.onchange=updateParams;prefix.onkeyup=prefix.onchange=updateParams;suffix.onkeyup=suffix.onchange=updateParams;whereleet.onkeyup=whereleet.onchange=updateParams;leetlevel.onkeyup=leetlevel.onchange=updateParams;hashalgo.onkeyup=hashalgo.onchange=updateParams;characters.onkeyup=characters.onchange=updateParams;cUpper.onkeyup=cUpper.onclick=cUpper.onchange=updateParams;cLower.onkeyup=cLower.onclick=cLower.onchange=updateParams;cNumber.onkeyup=cNumber.onclick=cNumber.onchange=updateParams;cSpecial.onkeyup=cSpecial.onclick=cSpecial.onchange=updateParams;cDefine.onkeyup=cDefine.onchange=updateParams;g('characterParts').onclick=updateParams;g('characterDefine').onclick=updateParams;g('characterCustion').onclick=updateParams;if(!(/KHTML|AppleWebKit|Opera/).test(navigator.userAgent)){i=navigator.userAgent.match(/MSIE\s([^;]*)/);if(i&&i[1]){i=parseFloat(i[1]);if(i==6.0){ie6=true;username.disabled=true;modifier.disabled=true;prefix.disabled=true;suffix.disabled=true;g('characterCustion').disabled=true;}}}
characters.disabled=true;hash='h';for(i=0;i<16;i++){hash+=hex[Math.floor(Math.random()*16)];}
updateParams();};function characterHandler(){var o;cTabs[0].className=cTabs[0].className.replace(/\btabHidden\b/g,'');cTabs[1].className=cTabs[1].className.replace(/\btabHidden\b/g,'');o=g('characterParts');characters.disabled=true;if(o.checked){cTabs[1].className=cTabs[1].className+' tabHidden';if(!cUpper.checked&&!cLower.checked&&!cNumber.checked&&!cSpecial.checked){g('bookmarkletRow').className+=' hidden';error.firstChild.nodeValue='You must have at least one character set checkbox enabled!';error.className='error';}
else{var mask=0;characters.value='';if(cUpper.checked){mask|=8;characters.value+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';}
if(cLower.checked){mask|=4;characters.value+='abcdefghijklmnopqrstuvwxyz';}
if(cNumber.checked){mask|=2;characters.value+='0123456789';}
if(cSpecial.checked){mask|=1;characters.value+='`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/';}
mask^=15;params=params.substr(0,4)+mask.toString(16)+params.substr(5);}}
else{o=g('characterDefine');if(o.checked){cTabs[0].className=cTabs[0].className+' tabHidden';params=params.substr(0,4)+cDefine.value+params.substr(5);characters.value='0123456789abcdef';}
else{cTabs[0].className=cTabs[0].className+' tabHidden';cTabs[1].className=cTabs[1].className+' tabHidden';params=params.substr(0,4)+'Z'+params.substr(5);characters.disabled=false;}}};function updateParams(){g('bookmarkletRow').className.replace(/\bhidden\b/g,'');error.className='hidden';characterHandler();bookmarklet.firstChild.nodeValue=bklname.value;bookmarklet.href='javascript:'+bkl.replace('faaaa000',params).replace('pwmextras',extras).replace('hpwmbklhash123456',hash).replace(' ','%20');if(ie6&&bookmarklet.href.legnth>477){g('bookmarkletRow').className+=' hidden';error.firstChild.nodeValue="Whoops, it seems the bookmarklet is too long. If you can't upgrade from IE6, consider using another browser.";error.className='error';}};function paramsUpdate(){updateParams();}