window._hpwmbklhash123456_v={id:'hpwmbklhash123456',ie:false,url:'url1.js',protocol:false,subdomain:false,domain:false,path:false,usetext:'',whereLeet:0,leetlevel:0,hash:'',characters:'',length:0,mphash:'',username:'',modifier:'',prefix:'',suffix:''};(function(){if(!window.console||!window.console.log){window.console={log:function(v){alert(v);}};}
var e=ehpwmbklhash123456,p=hpwmbklhash123456;hpwmbklhash123456=function(p,e){var h=window._hpwmbklhash123456_v;if(location.href.substring(0,h.url.length)==h.url){}
var i,f,g=function(id){return document.getElementById(id);},c={'0':'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','1':'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789','2':'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','3':'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz','4':'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','5':'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789','6':'ABCDEFGHIJKLMNOPQRSTUVWXYZ`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','7':'ABCDEFGHIJKLMNOPQRSTUVWXYZ','8':'abcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','9':'abcdefghijklmnopqrstuvwxyz0123456789','a':'abcdefghijklmnopqrstuvwxyz`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','b':'abcdefghijklmnopqrstuvwxyz','c':'0123456789`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','d':'0123456789','e':'`~!@#$%^&*()_-+={}|[]\\:";\'<>?,.\/','f':'0123456789abcdef'};if(!(/KHTML|AppleWebKit|Opera/).test(navigator.userAgent)){i=navigator.userAgent.match(/MSIE\s([^;]*)/);if(i&&i[1]){i=parseFloat(i[1]);if(i==6.0){h.ie=i;}}}
i=parseInt(p.charAt(0),16);h.protocol=(i&8)?true:false;h.subdomain=(i&4)?true:false;h.domain=(i&2)?true:false;h.path=(i&1)?true:false;h.whereLeet=parseInt(p.charAt(1),10);h.leetlevel=parseInt(p.charAt(2),10);h.hash=p.charAt(3);h.length=parseInt(p.substring(5),10);h.characters=p.charAt(4);if(h.characters=='Z'){h.characters=e.characters;}else{h.characters=c[h.characters];}
if(typeof e=='string'){}
else{if(e.mphash){h.mphash=e.mphash;}
if(e.username){h.username=e.username;}
if(e.modifier){h.modifier=e.modifier;}
if(e.prefix){h.prefix=e.prefix;}
if(e.suffix){h.suffix=e.suffix;}
if(e.usetext){h.usetext=e.usetext;}}
i=g(h.id);if(!i){i=document.createElement('div');i.id=h.id;i.style.position='absolute';i.style.border='1px solid #000';i.style.padding='3px';i.style.backgroundColor='#fff';i.style.color='#000';i.style.width='350px';f='<form id="'+h.id+'f" style="padding: 0;margin:0;text-align:center;">';f+='<div style="margin-bottom:3px;">';f+='<label id="l'+h.id+'mpw1" for="'+h.id+'mpw1" style="display:block; float:left; width:145px; text-align: right;">Master Password:</label>';f+='<input type="password" id="'+h.id+'mpw1" style="width:194px; text-align: left;" />';f+='</div>';if(!h.mphash){f+='<div style="clear:left;margin-bottom:3px;">';f+='<label id="l'+h.id+'mpw2" for="'+h.id+'mpw2" style="display:block; float:left; width:145px; text-align: right;">Confirm:</label>';f+='<input type="password" id="'+h.id+'mpw2" style="width:194px" text-align: left; />';f+='</div>';}
f+='<div style="clear:left;">';f+='<input type="submit" id="'+h.id+'pop" value="Populate" style="width:100%;" />';f+='</div>';f+='<div style="clear:left;">';f+='<input type="button" id="debug" value="Debug" style="display:block; float:left; width:145px;" />';f+='<input id="'+h.id+'pw" style="width:194px"/>';f+='</div>';f+='</form>';i.innerHTML=f;i.style.top='10px';i.style.left='10px';document.getElementsByTagName('body')[0].appendChild(i);g(h.id+'mpw1').focus();}
else{i.style.display='block';}};hpwmbklhash123456(p,e);})();